tweetsearch/urls.py
from django.conf.urls import patterns, url, include

urlpatterns = patterns('',
	url(r'^tweetsearch/', include('tweetsearchapp.urls', namespace="tweetsearchapp")),
)

tweetsearchapp/urls.py
from django.conf.urls import patterns, url

from tweetsearchapp.views import TweetSearch, TweetSearchResults

urlpatterns = patterns('',
	url(r'^$', TweetSearch.as_view(), name='search_tweets'),
	url(r'^search/$', TweetSearchResults.as_view(), name='search_results'),
)

tweetsearchapp/models.py
# python built-in imports
import datetime

# django built-in imports
from django.db import models



class TweetPhrase(models.Model):
    text = models.CharField(max_length=100)
    num_times_searched = models.IntegerField(default=0)
    last_search_datetime = models.DateTimeField('last searched', auto_now=True)
	
def update_search_model(tweet_phrase):
    """
    Updates number of times searched using phrase and last time of search.

    @return : returns 	
    """
    model, created = TweetPhrase.objects.get_or_create(
        text=tweet_phrase, defaults={'num_times_searched': 1})
    last_time_used = datetime.datetime.now()
    if not created:
        last_time_searched = model.last_search_datetime
        model.num_times_searched += 1
        model.last_search_datetime = datetime.datetime.now()
        model.save()

    return (model.num_times_searched, last_time_used)

tweetsearchapp/templates/tweet_search/search_tweets.html
{% load i18n %}
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <h2>{% trans "Enter search phrase:" %}</h2>
	<form id='searchForm' action={% url 'tweetsearchapp:search_results' %} method='GET'>
	  {% csrf_token %}
      <input type='text' name='tweet_phrase'>
      <input type='submit' value={% trans 'Search'%}>
    </form>
  </body>
</html>

tweetsearchapp/templates/tweet_search/tweet_results.html
{% load i18n %}
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <h2>{% blocktrans %}Search Results for "{{ tweet_phrase }}": {% endblocktrans %}</h2>
    {% if num_times_searched > 1 %}
      <h4>{% blocktrans %}Number of Times used: {{num_times_searched}}{% endblocktrans %}</h4>
      <h4>{% blocktrans %}Last time used: {{last_time_used}}{% endblocktrans %}</h4>
    {% endif %}
    <ul>
      {% for result in resultset %}
        <li><span>{% trans "Result" %}: {{ result.text }}</span></li>
      {% endfor %}
    </ul>
  </body>
</html>

tweetsearchapp/templates/tweet_search/validations.html
{% load i18n %}
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <h2>{% trans "Alert !!!!" %}</h2>
	<h1>{% trans "Search Phrase is Mandatory, Please go back and enter search phrase and click submit." %}</h1>
  </body>
</html>